version: '2'

services:
    db:
        image: percona:5.7
        volumes:
            - './.docker-data/db:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: 'd0ck3r!'
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'passw0rd!'
            TERM: '$TERM'
        ports:
            - '3306:3306'
    mail:
        image: tophfr/mailcatcher
        ports:
            - '1080:80'
    web:
        build:
            context: ./.docker-config/
            dockerfile: ./Dockerfile-php-apache-linux
            args:
                www_data_uid: "$DOCKER_UID"
                www_data_gid: "$DOCKER_GID"
        volumes:
            - '.:/app'
            - './.docker-config/vhost.conf:/etc/apache2/sites-available/000-default.conf'
            - './.docker-config/php.ini:/etc/php/7.1/php.ini'
            - './.docker-config/ssl:/etc/ssl/docker'
            # Uncomment the following line to enable xdebug
#            - './.docker-config/php-xdebug-phpstorm.ini:/etc/php/7.1/mods-available/xdebug-settings.ini'
        environment:
            COMPOSER_ALLOW_XDEBUG: '1'
            PHP_IDE_CONFIG: 'serverName=q-docker-php-apache'
            TERM: '$TERM'
        ports:
            - '80:80'
            - '443:443'
    nodejs:
        build:
            context: ./.docker-config/
            dockerfile: ./Dockerfile-nodejs-linux
            args:
                www_data_uid: "$DOCKER_UID"
                www_data_gid: "$DOCKER_GID"
        volumes:
            - '.:/app'
            - './.docker-data/nodejs:/var/www/nvm-volume'
        environment:
            TERM: '$TERM'
        ports:
            - '3000:3000'
